spring.application.name=demo1

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=app_musica
spring.data.mongodb.auto-index-creation=true

# MongoDB URI alternativa (comentada, usa esta si prefieres URI completa)
# spring.data.mongodb.uri=mongodb://localhost:27017/app_musica
